package com.llmapp.pr_review

import com.llmapp.api.ApiConfig
import com.llmapp.rag.data.GitHubApi
import kotlinx.coroutines.runBlocking
import java.io.File

/**
 * CLI entry point for running PR review from command line or GitHub Actions.
 *
 * Usage: PRNumber [outputDir] [model]
 *   - PRNumber: required, the PR number to review
 *   - outputDir: optional, default "build/reports/pr_review"
 *   - model: optional, default "mistral/mistral-large-latest"
 */
fun main(args: Array<String>) {
    if (args.isEmpty()) {
        println("Usage: PRReviewRunner <PRNumber> [outputDir] [model]")
        kotlin.system.exitProcess(1)
    }

    val prNumber = args[0].toIntOrNull()
    if (prNumber == null) {
        println("Error: PR number must be an integer, got '${args[0]}'")
        kotlin.system.exitProcess(1)
    }

    val outputDir = if (args.size > 1) File(args[1]) else File("build/reports/pr_review")
    val model = if (args.size > 2) args[2] else "mistral/mistral-large-latest"

    println("=" .repeat(60))
    println("  AI Code Review Pipeline")
    println("=" .repeat(60))
    println("  PR #$prNumber")
    println("  Model: $model")
    println("  Output: ${outputDir.absolutePath}")
    println()

    // Check GitHub token
    val token = GitHubApi.getToken()
    if (token == null) {
        println("Error: GitHub token not found. Set GITHUB_TOKEN env var or keys.properties")
        kotlin.system.exitProcess(1)
    }
    println("  GitHub token: ${token.take(10)}...")

    // Check LLM credentials
    try {
        val pwd = ApiConfig.getLlmUserPassword()
        println("  LLM credentials: ok")
    } catch (e: Exception) {
        println("Error: LLM credentials not found: ${e.message}")
        kotlin.system.exitProcess(1)
    }

    println()

    // Run review using PRReviewAgent2 with MCP + RAG
    runBlocking {
        try {
            println("  Step 1/3: Running AI review via PRReviewAgent2...")
            val startTime = System.currentTimeMillis()
            val agent = PRReviewAgent2()
            val progressMessages = mutableListOf<String>()
            val result = agent.review(
                prNumber = prNumber,
                onMessage = { msg -> progressMessages.add(msg) }
            )
            val elapsed = System.currentTimeMillis() - startTime

            for (msg in progressMessages) {
                println("    $msg")
            }
            println("    Done in ${elapsed}ms")
            println()

            println("  Step 2/3: Saving report...")
            outputDir.mkdirs()

            val mdContent = buildMarkdownReport(result)
            val mdFile = File(outputDir, "review_$prNumber.md")
            mdFile.writeText(mdContent)
            println("    Report: ${mdFile.absolutePath}")

            val jsonContent = buildJsonReport(result)
            val jsonFile = File(outputDir, "review_$prNumber.json")
            jsonFile.writeText(jsonContent)
            println("    JSON: ${jsonFile.absolutePath}")

            println()
            println("-" .repeat(60))
            println("  Review Summary")
            println("-" .repeat(60))
            println("  Score: ${result.score}/100")
            println("  PR #${result.prNumber}: ${result.prTitle}")
            println("-" .repeat(60))

        } catch (e: Exception) {
            println("  Error: ${e.message}")
            e.printStackTrace()
            kotlin.system.exitProcess(1)
        }
    }
}

private fun buildMarkdownReport(result: PRReviewAgent2.ReviewResult): String = buildString {
    appendLine("# AI Code Review: PR #${result.prNumber}")
    appendLine()
    appendLine("> **${result.prTitle}**")
    appendLine()
    appendLine("## Review")
    appendLine()
    appendLine("| Metric | Value |")
    appendLine("|--------|-------|")
    appendLine("| Overall Score | **${result.score}/100** |")
    appendLine()
    appendLine("## Findings")
    appendLine()
    appendLine(result.summary)
    appendLine()
    appendLine("---")
    appendLine("*Generated by AI Code Review Pipeline (MCP + RAG)*")
}

private fun buildJsonReport(result: PRReviewAgent2.ReviewResult): String {
    val sb = StringBuilder()
    sb.appendLine("{")
    sb.appendLine("  \"prNumber\": ${result.prNumber},")
    sb.appendLine("  \"prTitle\": \"${result.prTitle.replace("\"", "\\\"")}\",")
    sb.appendLine("  \"overallScore\": ${result.score},")
    sb.appendLine("  \"summary\": \"${result.summary.take(200).replace("\"", "\\\"").replace("\n", "\\n")}\"")
    sb.appendLine("}")
    return sb.toString()
}
